yaml
name: Hello purrfect-deadline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Мяу! Проект purrfect-deadline успешно собран! 🐾"
